name: Validate Sway Config

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Sway
      - name: Install sway and dependencies
        run: |
          sudo apt update
          sudo apt install -y sway xvfb
      - name: Run sway config validation
        run: |
          Xvfb :99 & export DISPLAY=:99
          bash share/scripts/validate_sway_config.sh
