name: Validate Sway Config

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Sway
      - name: Install Sway
        run: |
          apt update
          apt install sway -y
      
      # Validate config
      - name: Validate config
        run: bash share/scripts/validate_sway_config.sh
